name = "baseline"
compatibility_date = "2026-07-07"
pages_build_output_dir = "dist"

# After creating a new D1 database, add the binding here:
#
# [[d1_databases]]
# binding = "DB"
# database_name = "your-d1-database-name"
# database_id = "your-d1-database-id"

[vars]
APP_ENV = "production"
