name = "baseline"
compatibility_date = "2026-07-07"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "baseline"
database_id = "9d9136d8-e1f7-4766-815d-4750998641b6"

[vars]
APP_ENV = "production"
